#include "game.h"

#include <stdio.h>
#include <stdlib.h>
#include "gba.h"
#include "images/start.h"
#include "images/win.h"
#include "images/lose.h"
#include "images/smiley.h"


/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app.
typedef enum {
  START,
  INTRO,
  PLAY,
  WIN,
  LOSE,
} GBAState;

u32 colors[] = {RED, YELLOW, BLUE, GREEN};
// prototypes

int main(void) {
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial game state
  GBAState state = START;

  int rd = 1;
  int cd = 0;

  cube.row = CUBEROW;
  cube.col = CUBECOL;
  cube.size = CUBESIZE;
  cube.color = colors[rand() % 4];
  
  border.toprow = 0;
  border.topcol = 0;
  border.topcolor = RED;

  border.rightrow = 0;
  border.rightcol = 235;
  border.rightcolor = BLUE;

  border.leftrow = 0;
  border.leftcol = 0;
  border.leftcolor = YELLOW;

  border.bottomrow = 155;
  border.bottomcol = 0;
  border.bottomcolor = GREEN;

  border.width = WIDTH;
  border.height = HEIGHT;

  border.increment = 15;
  int count = 0;
  while (1) {
    currentButtons = BUTTONS;  // Load the current state of the buttons
    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      case START:
        waitForVBlank();
        drawFullScreenImageDMA(start);
        
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          drawIntro();
          state = INTRO;
        }
        // state = ?
        break;
      case INTRO:
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          fillScreenDMA(BLACK);
          drawBorder();
          count = 0;
          state = PLAY;
        }
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          fillScreenDMA(BLACK);
          state = START;
        }
        break;
      case PLAY:
        cube.row = cube.row + rd;
        cube.col = cube.col + cd;
        if(cube.row < 5 + border.increment * count) {
          if (cube.color == border.topcolor) {
            redrawBorder();
            count++;
          } else {
            fillScreenDMA(BLACK);
            state = LOSE;
          }
        } 
        if(cube.row > 149 - border.increment * count) {
          if (cube.color == border.bottomcolor) {
            redrawBorder();
            count++;
          } else {
            fillScreenDMA(BLACK);
            state = LOSE;
          }
        }
        if(cube.col < 6 + border.increment * count) {
          if (cube.color == border.leftcolor) {
            redrawBorder();
            count++;
          } else {
            fillScreenDMA(BLACK);
            state = LOSE;
          }
        }
        if(cube.col > 229 - (border.increment + 10) * count) {
          if (cube.color == border.rightcolor) {
            redrawBorder();
            count++;
          } else {
            fillScreenDMA(BLACK);
            state = LOSE;
          }
        }
        // Create cube
        drawRectDMA(cube.row, cube.col, cube.size, cube.size, cube.color);        
        waitForVBlank();
        drawRectDMA(cube.row, cube.col, cube.size, cube.size, BLACK);
        if (KEY_JUST_PRESSED(BUTTON_DOWN, currentButtons, previousButtons)) {
          rd = 1;
          cd = 0;
        }
        if (KEY_JUST_PRESSED(BUTTON_UP, currentButtons, previousButtons)) {
          rd = -1;
          cd = 0;
        }
        if (KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons)) {
          rd = 0;
          cd = -1;
        }
        if (KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons)) {
          rd = 0;
          cd = 1;
        }

        scoreTracker(count);
        if (count == 5) {
          fillScreenDMA(BLACK);
          state = WIN;
        }
        break;
      case WIN:
        drawFullScreenImageDMA(win);
        waitForVBlank();
        // state = ?
        break;
      case LOSE:
        drawFullScreenImageDMA(lose);
        waitForVBlank();
        // state = ?
        break;
    }
    if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
      state = START;
      reset();
      count = 0;
    }

    previousButtons = currentButtons;  // Store the current state of the buttons
  }


  return 0;
}

void drawIntro(void) {
  fillScreenDMA(BLACK);
  drawString(40, 72, "MATCH THE BORDER", WHITE);
  drawString(70, 55, "The rules are simple.", WHITE);
  drawString(80, 40, "Match the cube and the border.", WHITE);
  drawString(90, 58, "Press Start to begin.", WHITE);
}

void drawBorder(void) {
  fillScreenDMA(BLACK);
  drawRectDMA(border.toprow, border.topcol, border.width, 5, border.topcolor);
  drawRectDMA(border.rightrow, border.rightcol, 5, border.height, border.rightcolor);
  drawRectDMA(border.leftrow, border.leftcol, 5, border.height, border.leftcolor);
  drawRectDMA(border.bottomrow, border.bottomcol, border.width, 5, border.bottomcolor);
}

void redrawBorder(void) {
  border.toprow += 15;
  border.topcol += 15;
  
  border.bottomrow -= 15;
  border.bottomcol += 15;
  border.width -= 40;

  border.leftrow += 15;
  border.leftcol +=15;

  border.rightrow += 15;
  border.rightcol -= 25;
  border.height -= 30;
  drawBorder();
  cube.row = CUBEROW;
  cube.col = CUBECOL;

  cube.color = colors[rand() % 4];
}

void reset(void) {

  cube.row = CUBEROW;
  cube.col = CUBECOL;
  border.toprow = 0;
  border.topcol = 0;
  border.topcolor = RED;

  border.rightrow = 0;
  border.rightcol = 235;
  border.rightcolor = BLUE;

  border.leftrow = 0;
  border.leftcol = 0;
  border.leftcolor = YELLOW;

  border.bottomrow = 155;
  border.bottomcol = 0;
  border.bottomcolor = GREEN;

  border.width = WIDTH;
  border.height = HEIGHT;
}

void scoreTracker(int count) {
        if (count == 0) {
          drawString(5, 5, "Left: 5", WHITE);;
        }
        if (count == 1) {
          drawString(5, 5, "Left: 4", WHITE);
        }
        if (count == 2) {
          drawString(5, 5, "Left: 3", WHITE);
        }
        if (count == 3) {
          drawString(5, 5, "Left: 2", WHITE);
        }
        if (count == 4) {
          drawString(5, 5, "Left: 1", WHITE);
        }
        drawImageDMA(5, 215, 20, 20, smiley);
}